
-- =======================================================================================
--                                                                            Vendor Check
--                                                                            ============
CREATE TABLE VENDOR_CHECK ( 
	VENDOR_CHECK_ID BIGINT NOT NULL,
	TYPE_OF_CHAR char(3),
	TYPE_OF_VARCHAR varchar(32),
	TYPE_OF_LONG_VARCHAR long varchar,
	TYPE_OF_CLOB CLOB,
	TYPE_OF_DECIMAL_INTEGER DECIMAL(5, 0),
	TYPE_OF_DECIMAL_BIGINT DECIMAL(12, 0),
	TYPE_OF_DECIMAL_DECIMAL DECIMAL(5, 3),
	TYPE_OF_BIGINT BIGINT,
	TYPE_OF_INTEGER INTEGER,
	TYPE_OF_DATE DATE,
	TYPE_OF_TIMESTAMP TIMESTAMP,
	TYPE_OF_TIME TIME
	-- TYPE_OF_BLOB BLOB
	-- TYPE_OF_XML XML
) ;

-- =======================================================================================
--                                                                               Name Auto
--                                                                               =========
-- /= = = = = = = = = = = = = = = = = = = = = = =
-- for the test of auto-generated constraint name
-- = = = = = = = = = =/
CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_FOO (
	CONSTRAINT_NAME_AUTO_FOO_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_FOO_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_FOO_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_BAR (
	CONSTRAINT_NAME_AUTO_BAR_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_BAR_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_BAR_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_QUX (
	CONSTRAINT_NAME_AUTO_QUX_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_QUX_NAME VARCHAR(50) NOT NULL,
	UNIQUE (CONSTRAINT_NAME_AUTO_QUX_NAME)
) ;

CREATE TABLE VENDOR_CONSTRAINT_NAME_AUTO_REF (
	CONSTRAINT_NAME_AUTO_REF_ID NUMERIC(16) NOT NULL PRIMARY KEY,
	CONSTRAINT_NAME_AUTO_FOO_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_BAR_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_QUX_ID NUMERIC(16) NOT NULL,
	CONSTRAINT_NAME_AUTO_UNIQUE VARCHAR(50) NOT NULL,
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_FOO_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_FOO(CONSTRAINT_NAME_AUTO_FOO_ID),
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_BAR_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_BAR(CONSTRAINT_NAME_AUTO_BAR_ID),
	FOREIGN KEY(CONSTRAINT_NAME_AUTO_QUX_ID) REFERENCES VENDOR_CONSTRAINT_NAME_AUTO_QUX(CONSTRAINT_NAME_AUTO_QUX_ID),
	UNIQUE (CONSTRAINT_NAME_AUTO_UNIQUE)
) ;
